# Generated by Django 3.0.4 on 2020-03-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dept_name',
            field=models.CharField(choices=[('IT', 'IT'), ('Accounts', 'Accounts'), ('Sells', 'Sells')], default='select', max_length=10),
        ),
    ]
